server:
  port: 8888
spring:
  application:
    name: consul-zuul
  boot:
    admin:
      client:
        url:http://localhost:9999
  cloud:
    consul:
      discovery:
        register: true
        service-name: zuul-proxy
      host: 127.0.0.1
      port: 8500
zuul:
  prefix: /api
  routes:
    E_Commerce:
      serviceId: e-commerce
    #Student:
     # path: /student/**
      #serviceId: student-service
    #School:
     # path: /school/**
     # service-id: school-service
      
